
- name: remove_html
  ansible.builtin.include_tasks: 
    file: remove_html.yml
  become: true

- name: copy_html
  ansible.builtin.include_tasks: 
    file: copy_html.yml
  become: true

- name: stope_nginx
  ansible.builtin.include_tasks: 
    file: stop_nginx.yml
  become: true

- name: start_nginx
  ansible.builtin.include_tasks: 
    file: start_nginx.yml
  become: true
