
- include_tasks: remove_html.yml
  become: true

- include_tasks: copy_html.yml
  become: true

- include_tasks: stop_nginx.yml
  become: true

- include_tasks: start_nginx.yml
  become: true
