
- ansible.builtin.include_tasks: 
    file: remove_html.yml

- ansible.builtin.include_tasks: 
    file: copy_html.yml

- ansible.builtin.include_tasks: 
    file: stop_nginx.yml

- ansible.builtin.include_tasks: 
    file: start_nginx.yml
